export type ExpansionCatalogRow = {
  slug: string;
  title: string;
  prereqSlugs: string[];
  summary: string;
  lesson: string;
  practice: string;
  outcome: string;
};

type Lane = {
  sourceKey: string;
  subjectIds: string[];
  rows: ExpansionCatalogRow[];
};

const lane = (
  sourceKey: string,
  subjectIds: string[],
  rows: ExpansionCatalogRow[],
): Lane => ({ sourceKey, subjectIds, rows });

export const EXPANSION_LANES: Lane[] = [
  lane('learning', ['learning-science', 'focus'], [
    { slug: 'learning-science-foundations', title: 'Learning Science Foundations', prereqSlugs: ['thinking-and-cognition'], summary: 'Learn how attention, memory, practice, and feedback work together during learning.', lesson: 'Learning improves through repeated contact with an idea, active recall, useful feedback, and a setting that makes practice possible. A study plan becomes stronger when it names the task, the evidence of learning, and the next adjustment.', practice: 'Choose one class topic. Write what you can explain now, test yourself without notes, check the result, and plan one short return session.', outcome: 'describe four parts of a learning system and connect each part to a study choice' },
    { slug: 'metacognition-for-learners', title: 'Metacognition for Learners', prereqSlugs: ['learning-science-foundations'], summary: 'Use self-observation to compare what feels familiar with what you can actually retrieve.', lesson: 'Metacognition is thinking about your own thinking. Predictions, checks, and reflections reveal gaps between confidence and performance, giving you information for the next study step.', practice: 'Before a quiz, predict your score on three topics. Afterward, compare the prediction with the result and write one change for your next session.', outcome: 'compare a confidence judgment with a performance check and choose a useful adjustment' },
    { slug: 'spaced-practice', title: 'Spaced Practice', prereqSlugs: ['metacognition-for-learners', 'memory-and-recall'], summary: 'Build memory over several shorter sessions by returning to ideas across time.', lesson: 'Spacing separates practice across days or sessions. Each return asks the brain to reconstruct the idea, which makes the next retrieval more informative than one long rereading block.', practice: 'Split one study task across three calendar slots. Record what you remembered at the start of each slot and what required a prompt.', outcome: 'design a short spaced-practice schedule and explain why the returns matter' },
    { slug: 'retrieval-practice', title: 'Retrieval Practice', prereqSlugs: ['spaced-practice'], summary: 'Strengthen learning by pulling an idea from memory before checking the source.', lesson: 'Retrieval practice uses questions, blank-page summaries, flashcards, or explanations from memory. Feedback closes the loop and turns an error into a target for another attempt.', practice: 'Close your notes and answer five questions about one lesson. Mark each answer as clear, partial, or missing, then revisit only the partial and missing ideas.', outcome: 'use a retrieval prompt and interpret the result as information for the next practice' },
    { slug: 'desirable-difficulty', title: 'Desirable Difficulty', prereqSlugs: ['retrieval-practice'], summary: 'Recognize why a manageable challenge can produce stronger learning than an effortless review.', lesson: 'A useful difficulty slows immediate performance while increasing the information gained from practice. Mixed questions, delayed review, and changing examples can make learning feel harder while building flexible recall.', practice: 'Compare one easy rereading session with one closed-note question session. Record immediate comfort and later recall separately.', outcome: 'identify a manageable challenge and distinguish immediate ease from later learning' },
    { slug: 'feedback-and-learning', title: 'Feedback and Learning', prereqSlugs: ['retrieval-practice'], summary: 'Turn corrections into specific information about the next action to take.', lesson: 'Feedback works best when it arrives close enough to the attempt to guide revision and names the gap between the goal and the current work. Encouragement can support persistence while details guide change.', practice: 'Ask for feedback on one piece of work. Sort each comment into accuracy, strategy, or presentation, then choose one revision.', outcome: 'translate feedback into a concrete revision or practice step' },
    { slug: 'goals-for-learning', title: 'Goals for Learning', prereqSlugs: ['learning-science-foundations', 'values-clarification'], summary: 'Set learning goals that name a skill, a reason, a measure, and a next action.', lesson: 'A useful goal connects a valued purpose with an observable behavior. Process goals such as solving five problems or explaining one concept create more control than a distant outcome alone.', practice: 'Rewrite one vague goal as a skill plus a time, place, and evidence of progress. Share the plan with a trusted person if support would help.', outcome: 'turn a broad learning wish into an observable process goal' },
    { slug: 'self-regulated-learning', title: 'Self-Regulated Learning', prereqSlugs: ['goals-for-learning', 'metacognition-for-learners'], summary: 'Plan, monitor, and revise a learning cycle instead of relying on motivation alone.', lesson: 'Self-regulated learning moves through planning, action, monitoring, and reflection. The learner adjusts the task, time, environment, or support when the evidence calls for a change.', practice: 'Plan a 25-minute session, monitor one distraction, and review what helped you continue. Change one part before the next session.', outcome: 'describe the four stages of a self-regulated learning cycle' },
    { slug: 'transfer-and-application', title: 'Transfer and Application', prereqSlugs: ['feedback-and-learning', 'self-regulated-learning'], summary: 'Carry an idea into a new example, setting, or problem.', lesson: 'Transfer happens when a learner recognizes a useful structure across different examples. Practice across contexts, explanation of the underlying principle, and comparison of cases can make that recognition easier.', practice: 'Take one concept from class and apply it to a household, community, or personal example. Explain which parts match and which parts differ.', outcome: 'apply one learned idea to a new context and explain the connection' },
    { slug: 'learning-project-design', title: 'Learning Project Design', prereqSlugs: ['transfer-and-application', 'study-design-basics'], summary: 'Design a small learning project with a question, practice loop, evidence, and reflection.', lesson: 'A learning project turns curiosity into a bounded cycle. It names what will be learned, how practice will happen, what evidence will count, and how the result will shape the next version.', practice: 'Draft a one-week project with one question, three practice sessions, one artifact, and one reflection prompt.', outcome: 'design a short learning project with a clear question and evidence of progress' },
  ]),
  lane('neuroscience', ['neuroscience', 'foundations'], [
    { slug: 'brain-and-behavior', title: 'Brain and Behavior', prereqSlugs: ['states-of-consciousness', 'thinking-and-cognition'], summary: 'Build a careful map of how brain processes, body states, and environments relate to behavior.', lesson: 'Behavior emerges from interacting brain, body, history, and context. A brain explanation can add useful detail while leaving room for learning, relationships, culture, and current conditions.', practice: 'Choose one everyday behavior and list a brain process, body signal, environmental cue, and learned history that could shape it.', outcome: 'explain why behavior usually has multiple interacting influences' },
    { slug: 'neurons-and-signals', title: 'Neurons and Signals', prereqSlugs: ['brain-and-behavior'], summary: 'Learn how nerve cells communicate through electrical and chemical signals.', lesson: 'Neurons receive information, integrate signals, and communicate with other cells. This cellular vocabulary helps explain how sensation, movement, attention, and learning involve networks rather than one isolated switch.', practice: 'Draw a simple neuron-to-neuron pathway and label input, signal, connection, and response.', outcome: 'describe the basic path from a neural input to a communicated signal' },
    { slug: 'brain-plasticity', title: 'Brain Plasticity', prereqSlugs: ['neurons-and-signals', 'memory-and-recall'], summary: 'Explore how experience, practice, and changing conditions can shape brain networks.', lesson: 'Plasticity describes change in nervous-system structure or function across time. It supports learning and adaptation, while the size and meaning of a change depend on the task, person, and evidence.', practice: 'Track one skill over five short sessions. Record the practice, the task measure, and one condition that may have influenced performance.', outcome: 'explain plasticity as experience-related change with context-dependent limits' },
    { slug: 'executive-functions', title: 'Executive Functions', prereqSlugs: ['brain-and-behavior', 'attention-basics'], summary: 'Study planning, working memory, inhibition, and flexible switching as coordinated control skills.', lesson: 'Executive functions help a person hold a goal, select information, pause a response, and shift strategies. They operate within energy, emotion, environment, and task demands.', practice: 'Choose a task with two steps. Write the goal, remove one distraction, use a timer, and note where the plan needed revision.', outcome: 'identify planning, working memory, inhibition, and flexibility in an everyday task' },
    { slug: 'reward-and-motivation', title: 'Reward and Motivation', prereqSlugs: ['brain-and-behavior', 'motivation-and-emotion'], summary: 'Connect reward signals, expectations, effort, and context to the experience of motivation.', lesson: 'Motivation changes with expected value, effort, feedback, timing, and social meaning. Reward systems influence learning and action while working alongside goals and reflection.', practice: 'Map one task with an immediate reward, a delayed benefit, the effort required, and one change that could make starting easier.', outcome: 'describe several factors that shape motivation for a task' },
    { slug: 'stress-response-systems', title: 'Stress Response Systems', prereqSlugs: ['brain-and-behavior', 'stress-basics'], summary: 'Learn how the body and brain coordinate responses to challenge and recovery.', lesson: 'Stress responses mobilize attention and energy for a demand. Recovery systems help return the body toward a flexible baseline, and repeated demands can interact with sleep, support, and perceived control.', practice: 'Describe one short challenge using three stages: signal, response, and recovery. Add one support that could make recovery easier.', outcome: 'map a stress response from trigger through recovery and name a contextual support' },
    { slug: 'sleep-and-the-brain', title: 'Sleep and the Brain', prereqSlugs: ['sleep-basics', 'brain-and-behavior'], summary: 'Connect sleep cycles, memory, attention, and daily routines through a careful science lens.', lesson: 'Sleep includes changing stages and serves several brain and body functions. Individual needs and schedules vary, so a useful lesson emphasizes patterns, observations, and support for persistent problems.', practice: 'Keep a one-week sleep and learning log with sleep timing, one focus task, and one environmental note.', outcome: 'describe why sleep is relevant to learning while respecting individual variation' },
    { slug: 'embodied-cognition', title: 'Embodied Cognition', prereqSlugs: ['brain-and-behavior', 'movement-and-mood'], summary: 'Explore how body position, movement, sensation, and environment participate in thinking.', lesson: 'Cognition unfolds through brain, body, and surroundings. Movement and sensory cues can change what information is available for a task, while the size of any effect depends on context and measurement.', practice: 'Complete the same simple thinking task seated and while walking slowly. Record the task result and how each setting felt.', outcome: 'give an example of how body and environment can participate in cognition' },
    { slug: 'neurodiversity-and-learning', title: 'Neurodiversity and Learning', prereqSlugs: ['brain-and-behavior', 'adhd-and-focus'], summary: 'Study variation in attention, perception, communication, and learning through an access-centered lens.', lesson: 'Neurodiversity describes natural variation in nervous systems and ways of processing the world. Learning environments can reduce barriers through clear instructions, flexible tools, and respect for different strengths.', practice: 'Choose one assignment and create two access options, such as audio plus text or a quiet plus collaborative workspace.', outcome: 'identify an access change that supports varied ways of learning' },
    { slug: 'brain-science-claims', title: 'Reading Brain Science Claims', prereqSlugs: ['brain-plasticity', 'science-and-evidence'], summary: 'Evaluate brain-based explanations by checking the measure, sample, method, and practical conclusion.', lesson: 'Brain images and neuroscience terms can make a claim sound certain. Strong reading separates what researchers measured from what a headline infers and checks whether the result applies to daily behavior.', practice: 'Find one brain-related claim and write the measured variable, the sample, the method, and the practical claim in separate lines.', outcome: 'separate a neuroscience measurement from a broader claim about behavior' },
  ]),
  lane('emotional', ['emotional-regulation', 'foundations'], [
    { slug: 'emotion-regulation-models', title: 'Emotion Regulation Models', prereqSlugs: ['motivation-and-emotion', 'emotional-vocabulary'], summary: 'Compare ways people influence the timing, intensity, meaning, and expression of emotion.', lesson: 'Emotion regulation can involve changing a situation, shifting attention, reappraising meaning, accepting experience, or choosing an action. Different strategies fit different conditions.', practice: 'Map one recent emotion by situation, body signal, interpretation, action urge, and chosen response.', outcome: 'name several points in an emotion process where regulation can occur' },
    { slug: 'triggers-and-appraisals', title: 'Triggers and Appraisals', prereqSlugs: ['emotion-regulation-models'], summary: 'Notice how interpretation helps shape the emotional meaning of an event.', lesson: 'A trigger is an event or cue, while an appraisal is the meaning assigned to it. Two people can respond differently because their histories, goals, and available information differ.', practice: 'Write two possible appraisals for one ambiguous event and predict how each would shape an action urge.', outcome: 'distinguish an event from the interpretation attached to it' },
    { slug: 'acceptance-and-reappraisal', title: 'Acceptance and Reappraisal', prereqSlugs: ['triggers-and-appraisals', 'cognitive-reframing'], summary: 'Use acceptance and meaning-shifts as distinct tools for responding to difficult feelings.', lesson: 'Acceptance makes room for present experience while reappraisal changes the interpretation of a situation. Both can support deliberate action when used with accurate facts and clear boundaries.', practice: 'Describe one feeling in neutral language, then write one grounded reappraisal that fits the available evidence.', outcome: 'compare acceptance with reappraisal and choose a fitting practice' },
    { slug: 'rumination-and-attention', title: 'Rumination and Attention', prereqSlugs: ['triggers-and-appraisals', 'attention-basics'], summary: 'Study repetitive thought loops and how attention can return to a chosen task.', lesson: 'Rumination repeats a concern without producing a next action. Attention cues, time limits, writing, movement, and social support can create a transition from looping to a bounded response.', practice: 'When a thought loop appears, label the topic, write one actionable step, and choose a return cue for the next ten minutes.', outcome: 'recognize a repetitive thought loop and create one bounded next action' },
    { slug: 'self-compassion-science', title: 'Self-Compassion Science', prereqSlugs: ['compassion-and-kindness-practice'], summary: 'Examine self-kindness, shared humanity, and clear awareness as responses to mistakes.', lesson: 'Self-compassion combines accurate attention to difficulty with language that supports learning and dignity. It can coexist with accountability, repair, and changed behavior.', practice: 'Rewrite one harsh self-judgment as a factual description, a caring response, and one repair step.', outcome: 'connect self-compassion with accountability and a concrete next action' },
    { slug: 'values-and-emotion', title: 'Values and Emotion', prereqSlugs: ['values-clarification', 'emotion-regulation-models'], summary: 'Use values to choose behavior when emotion supplies urgency but several actions remain possible.', lesson: 'Emotions can signal what matters, while values help organize a response across time. A values-based choice considers impact, relationships, and the kind of person or community the action supports.', practice: 'Name the value inside one strong feeling and choose a behavior that expresses it with a clear boundary.', outcome: 'use a value to guide one action during emotional pressure' },
    { slug: 'anger-as-information', title: 'Anger as Information', prereqSlugs: ['emotion-regulation-models'], summary: 'Treat anger as a signal to investigate needs, limits, expectations, and possible action.', lesson: 'Anger can point toward perceived unfairness, blocked goals, threat, or violated boundaries. The signal deserves attention while the chosen behavior still needs care and proportion.', practice: 'Describe an anger event, the expectation underneath it, the boundary involved, and one response that protects safety.', outcome: 'separate anger as information from the behavior chosen afterward' },
    { slug: 'shame-and-self-talk', title: 'Shame and Self-Talk', prereqSlugs: ['self-compassion-science'], summary: 'Recognize identity-level self-judgments and replace them with specific, changeable descriptions.', lesson: 'Shame can compress a mistake into a global judgment about the self. Specific language restores detail: what happened, what mattered, what can be repaired, and what support is available.', practice: 'Take one self-critical sentence and rewrite it as an observable event plus a next step.', outcome: 'turn a global self-judgment into a specific and actionable description' },
    { slug: 'emotional-boundaries', title: 'Emotional Boundaries', prereqSlugs: ['self-compassion-science', 'social-connectedness'], summary: 'Set clear limits around responsibility, availability, privacy, and emotional labor.', lesson: 'A boundary communicates what a person can offer, what they need, and what action they will take. Good boundaries respect another person while preserving safety and agency.', practice: 'Write one boundary using three parts: situation, limit, and next action. Practice the sentence in a calm voice.', outcome: 'write a clear boundary that includes a limit and a next action' },
    { slug: 'regulation-plan', title: 'Personal Regulation Plan', prereqSlugs: ['acceptance-and-reappraisal', 'emotional-boundaries'], summary: 'Assemble a flexible plan for noticing emotion, choosing a tool, and reviewing what happened.', lesson: 'A regulation plan turns scattered strategies into a sequence: notice, name, assess safety, choose, act, and review. Plans stay flexible because context and capacity change.', practice: 'Create a one-page plan with three early signals, two low-risk tools, one support person, and one review question.', outcome: 'build a personal regulation plan with signals, tools, support, and review' },
  ]),
  lane('coping', ['coping', 'emotional-regulation'], [
    { slug: 'coping-toolkit', title: 'Coping Toolkit', prereqSlugs: ['stress-basics', 'self-care-techniques'], summary: 'Build a menu of coping tools for body, attention, problem solving, and connection.', lesson: 'Coping tools work through different routes. A short walk may change body energy, a plan may address a controllable problem, and connection may provide perspective or practical help.', practice: 'Sort five strategies into body, attention, problem solving, and connection. Choose one tool for a small stressor.', outcome: 'match a coping tool to the type of demand it addresses' },
    { slug: 'controllable-and-uncontrollable-stress', title: 'Controllable and Uncontrollable Stress', prereqSlugs: ['coping-toolkit', 'stress-lifestyle-and-health'], summary: 'Separate the part of a stressor you can influence from the part that calls for support and adaptation.', lesson: 'Perceived control changes the strategy that fits. Direct action helps with a solvable task, while acceptance, support, and recovery help when the central condition cannot be changed immediately.', practice: 'Draw two circles around a current stressor: influence and outside influence. Choose one action for each circle.', outcome: 'separate influence from outside influence and choose a fitting coping route' },
    { slug: 'problem-focused-coping', title: 'Problem-Focused Coping', prereqSlugs: ['controllable-and-uncontrollable-stress'], summary: 'Use planning, information, communication, and action to address a changeable stressor.', lesson: 'Problem-focused coping begins with a clear definition of the problem and ends with a testable next step. It works best when the person has some control over the demand.', practice: 'Turn one stressor into a problem statement, list three options, choose one, and set a review time.', outcome: 'turn a controllable stressor into a small action plan' },
    { slug: 'emotion-focused-coping', title: 'Emotion-Focused Coping', prereqSlugs: ['controllable-and-uncontrollable-stress'], summary: 'Use soothing, meaning, expression, and support when the emotional load needs attention.', lesson: 'Emotion-focused coping changes the relationship to a stressful feeling. It can include rest, breathing, journaling, perspective, creative expression, and connection while the situation unfolds.', practice: 'Choose one emotion-focused tool, use it for five minutes, and record the emotion, body state, and next decision.', outcome: 'choose an emotion-focused tool and describe what it changed' },
    { slug: 'resilience-factors', title: 'Resilience Factors', prereqSlugs: ['coping-toolkit', 'social-connectedness'], summary: 'Study the supports and practices that help people adapt after challenge.', lesson: 'Resilience grows from interacting resources such as relationships, routines, skills, meaning, access to help, and opportunities to recover. Each person and setting shapes how adaptation unfolds.', practice: 'Make a support map with one internal skill, one relationship, one routine, one community resource, and one barrier.', outcome: 'map several resources that can support adaptation during challenge' },
    { slug: 'stress-and-recovery-cycle', title: 'Stress and Recovery Cycle', prereqSlugs: ['sleep-and-recovery', 'controllable-and-uncontrollable-stress'], summary: 'Track demand, activation, recovery, and renewed capacity across a week.', lesson: 'Stress and recovery interact over time. A day with repeated demands can require deliberate transitions, sleep, food, movement, and connection to restore capacity for the next task.', practice: 'Draw a seven-day timeline and mark high demand, recovery windows, and one place where a transition could improve.', outcome: 'describe a weekly stress and recovery pattern and identify one transition point' },
    { slug: 'uncertainty-and-stress', title: 'Uncertainty and Stress', prereqSlugs: ['stress-and-recovery-cycle', 'anxiety-basics'], summary: 'Use information, boundaries, and flexible plans when the future remains unclear.', lesson: 'Uncertainty creates space for prediction, worry, and preparation. A useful response separates what is known, what is possible, what can be checked, and what deserves a support plan.', practice: 'Write four columns for a current uncertainty: known, unknown, next check, and support if the outcome is difficult.', outcome: 'organize uncertainty into facts, questions, next checks, and support' },
    { slug: 'trauma-informed-support', title: 'Trauma-Informed Support', prereqSlugs: ['coping-toolkit', 'coping-with-traumatic-events'], summary: 'Use safety, choice, trust, and collaboration when supporting someone after a difficult event.', lesson: 'Trauma-informed support prioritizes safety, consent, predictable information, and the person’s control over their story. Supporters can listen and connect people with qualified help without taking on a clinical role.', practice: 'Rewrite one helping response to include choice, privacy limits, a practical offer, and a trusted support route.', outcome: 'name four principles for respectful support after a difficult event' },
    { slug: 'help-seeking-and-support', title: 'Help-Seeking and Support', prereqSlugs: ['mental-health-check-in', 'social-connectedness'], summary: 'Plan how to recognize a need, choose a trusted person, and ask for specific support.', lesson: 'Help-seeking is a practical skill. A clear request can describe what is happening, what has already been tried, and what kind of listening, information, or action would help.', practice: 'Write a three-sentence support request and identify two people or services who could receive it.', outcome: 'create a specific support request and identify an appropriate route' },
    { slug: 'personal-coping-plan', title: 'Personal Coping Plan', prereqSlugs: ['resilience-factors', 'help-seeking-and-support'], summary: 'Combine early signals, coping tools, support routes, and review into one usable plan.', lesson: 'A coping plan works best before a high-pressure moment. It names early signs, low-risk actions, people to contact, and a review step that keeps the plan current.', practice: 'Make a pocket-sized plan with three signals, three tools, two supports, and one escalation step for serious distress.', outcome: 'assemble a coping plan with tools, supports, and a review step' },
  ]),
  lane('mindfulness', ['mindfulness', 'focus'], [
    { slug: 'attention-anchors', title: 'Attention Anchors', prereqSlugs: ['meditation-foundations', 'mindful-breathing'], summary: 'Compare breath, sound, sensation, movement, and visual anchors for attention practice.', lesson: 'An anchor gives the mind a repeatable place to return. The best anchor is usable in the person’s setting and can be noticed with enough detail to support a return.', practice: 'Try two anchors for two minutes each. Record which details were easiest to notice and which supported a return.', outcome: 'choose and describe an anchor that fits a short attention practice' },
    { slug: 'open-monitoring', title: 'Open Monitoring', prereqSlugs: ['attention-anchors'], summary: 'Notice thoughts, feelings, and sensations as changing events in awareness.', lesson: 'Open monitoring widens attention to what appears instead of holding one object as the primary focus. Labels can add clarity while the observer keeps returning to present experience.', practice: 'Set a three-minute timer and label each event as thought, feeling, sensation, sound, or urge.', outcome: 'use simple labels to observe changing experience during a short practice' },
    { slug: 'body-scan-practice', title: 'Body Scan Practice', prereqSlugs: ['attention-anchors'], summary: 'Move attention through the body and describe sensations with curiosity and precision.', lesson: 'A body scan uses a sequence to notice pressure, temperature, tension, movement, and neutral areas. Sensation descriptions create information while interpretation remains open.', practice: 'Move attention from feet to head for five minutes. Record three sensations and one change across the practice.', outcome: 'describe bodily sensations with specific, observable language' },
    { slug: 'mindful-movement', title: 'Mindful Movement', prereqSlugs: ['body-scan-practice', 'movement-and-mood'], summary: 'Use movement, balance, and sensation as a route into present-moment awareness.', lesson: 'Mindful movement combines a physical action with attention to pace, effort, balance, breath, and surroundings. The practice can be adapted to many abilities and settings.', practice: 'Walk or stretch slowly for five minutes. Notice three movement details and one moment when attention wandered.', outcome: 'apply an attention anchor during a safe and adaptable movement practice' },
    { slug: 'mindful-eating', title: 'Mindful Eating', prereqSlugs: ['mindfulness-in-daily-life', 'nutrition-basics'], summary: 'Observe hunger cues, sensory details, pace, and context around eating.', lesson: 'Mindful eating brings attention to taste, texture, pace, body signals, culture, access, and emotion. It supports observation and respect for individual needs rather than a single ideal eating pattern.', practice: 'Choose one snack or meal and record sensory details, pace, context, and the body cues you noticed.', outcome: 'describe several factors that shape an eating experience' },
    { slug: 'loving-kindness-practice', title: 'Loving-Kindness Practice', prereqSlugs: ['compassion-and-kindness-practice'], summary: 'Use brief phrases of care and goodwill toward yourself and other people.', lesson: 'Loving-kindness practices direct intentional goodwill toward different people, including the self. The phrases can be adapted to fit culture, belief, and personal comfort.', practice: 'Choose three respectful phrases and repeat them for two minutes, then write one behavior that expresses care today.', outcome: 'connect a goodwill intention with one concrete caring behavior' },
    { slug: 'mindfulness-and-emotion', title: 'Mindfulness and Emotion', prereqSlugs: ['open-monitoring', 'emotion-regulation-models'], summary: 'Use present-moment awareness to notice emotion before choosing a response.', lesson: 'Mindfulness creates a pause for noticing body signals, thoughts, and action urges. The pause can support a deliberate response while preserving the information inside the emotion.', practice: 'During one mild emotion, write the body signal, thought, urge, and chosen action in four short lines.', outcome: 'map an emotion with present-moment attention before acting' },
    { slug: 'mindfulness-and-study', title: 'Mindfulness and Study', prereqSlugs: ['mindfulness-in-daily-life', 'retrieval-practice'], summary: 'Use brief attention practices to begin, pause, and return during study sessions.', lesson: 'A study transition can use one breath, a clear intention, and a defined task. Mindfulness supports the return to work, while retrieval and feedback provide the learning evidence.', practice: 'Begin two study sessions with a one-minute arrival practice and compare the task you completed in each session.', outcome: 'use a brief attention transition before an evidence-based study task' },
    { slug: 'digital-mindfulness', title: 'Digital Mindfulness', prereqSlugs: ['mindfulness-in-daily-life'], summary: 'Notice how notifications, interfaces, and habits shape attention during digital activity.', lesson: 'Digital environments contain cues designed to invite checking, scrolling, and switching. A mindful pause can reveal the cue, the urge, the goal, and the choice available.', practice: 'For one hour, record three notification cues and write the goal you had before each check.', outcome: 'identify a digital attention cue and name a deliberate response' },
    { slug: 'meditation-practice-design', title: 'Meditation Practice Design', prereqSlugs: ['attention-anchors', 'study-design-basics'], summary: 'Design a short meditation practice with a clear aim, safe setting, and observation plan.', lesson: 'A practice design names the anchor, duration, context, instructions, and signals for adjustment. Observation helps a learner understand fit without turning a personal trial into a universal claim.', practice: 'Write a one-week practice plan with three sessions, one anchor, one duration, and two observations to record.', outcome: 'design a bounded meditation practice with a clear observation plan' },
  ]),
  lane('wellness', ['wellness-science', 'habits'], [
    { slug: 'health-behavior-basics', title: 'Health Behavior Basics', prereqSlugs: ['wellness-as-a-system'], summary: 'Study how cues, choices, resources, routines, and social context shape health behavior.', lesson: 'Health behavior reflects personal choices and the conditions around them. A useful plan examines the cue, action, reward, access, social setting, and barrier together.', practice: 'Map one routine from cue to action to result, then identify one environmental change that could support it.', outcome: 'describe personal and environmental influences on a health behavior' },
    { slug: 'habit-cues-and-context', title: 'Habit Cues and Context', prereqSlugs: ['health-behavior-basics', 'operant-conditioning-and-habits'], summary: 'Recognize the places, times, objects, and feelings that make a behavior easier to start.', lesson: 'Habits become more predictable when cues and contexts repeat. Changing the cue, reducing friction, or preparing the first step can change the routine’s starting conditions.', practice: 'Choose one habit and list its usual cue, first action, context, and reward. Change one cue for three days.', outcome: 'identify the cue and context that start a repeatable behavior' },
    { slug: 'implementation-intentions', title: 'Implementation Intentions', prereqSlugs: ['habit-cues-and-context'], summary: 'Turn a goal into an if-then plan linked to a specific situation.', lesson: 'An implementation intention pairs a recognizable situation with a planned response. The format moves a decision closer to the moment when action becomes possible.', practice: 'Write three if-then plans for one goal, then choose the plan with the clearest cue and smallest first step.', outcome: 'write an if-then plan with a specific cue and response' },
    { slug: 'environment-and-wellness', title: 'Environment and Wellness', prereqSlugs: ['wellness-as-a-system', 'stress-lifestyle-and-health'], summary: 'Examine how rooms, schedules, technology, transportation, and access shape everyday well-being.', lesson: 'Wellness happens inside environments. Light, noise, privacy, food access, movement options, safety, and social expectations can support or strain a routine.', practice: 'Audit one daily setting for cues, barriers, supports, and one change that could improve access.', outcome: 'identify an environmental factor that shapes a wellness routine' },
    { slug: 'social-wellness', title: 'Social Wellness', prereqSlugs: ['social-connectedness', 'wellness-as-a-system'], summary: 'Map connection, belonging, reciprocity, boundaries, and support across a person’s week.', lesson: 'Social wellness includes opportunities to connect, contribute, receive help, and rest from social demand. Different relationships can meet different needs.', practice: 'Create a weekly connection map with one nourishing interaction, one support request, and one boundary.', outcome: 'describe several parts of a balanced social support system' },
    { slug: 'nutrition-basics', title: 'Nutrition Basics', prereqSlugs: ['wellness-as-a-system', 'mental-health-foundations'], summary: 'Learn how food, hydration, access, culture, and routines relate to energy and daily functioning.', lesson: 'Nutrition includes nutrients, eating patterns, food access, culture, budget, schedule, and enjoyment. Individual needs vary, so basic literacy should lead to informed questions rather than rigid rules.', practice: 'Record one day of meals, hydration, timing, energy, and context. Look for a pattern and one question to explore.', outcome: 'name several factors that shape nutrition and daily energy' },
    { slug: 'food-and-energy', title: 'Food and Energy', prereqSlugs: ['nutrition-basics'], summary: 'Connect meal timing, hydration, sleep, movement, and energy observations.', lesson: 'Energy changes across a day for many reasons. A useful observation log tracks food and hydration alongside sleep, activity, stress, and task demands.', practice: 'Track energy before two similar tasks on two days and include sleep, food timing, hydration, and stress as context.', outcome: 'interpret an energy observation with multiple possible influences' },
    { slug: 'movement-recovery-balance', title: 'Movement and Recovery Balance', prereqSlugs: ['movement-and-mood', 'sleep-and-recovery'], summary: 'Plan movement, rest, and recovery as a flexible system that changes with demand.', lesson: 'Movement can support capacity while recovery restores it. A balanced plan adapts intensity, duration, sleep, and rest to the person and the current context.', practice: 'Design a week with two movement options, two recovery options, and a rule for adjusting when capacity changes.', outcome: 'create an adaptable movement and recovery plan' },
    { slug: 'stress-sleep-interaction', title: 'Stress and Sleep Interaction', prereqSlugs: ['sleep-basics', 'stress-basics'], summary: 'Observe how stress and sleep can influence one another across repeated days.', lesson: 'Stress can affect sleep timing and quality, while sleep changes can affect attention, mood, and coping capacity. A log can show patterns while leaving causes open for investigation.', practice: 'Track seven days of sleep timing, stress rating, and one coping action. Review the sequence instead of one isolated night.', outcome: 'describe a possible stress and sleep pattern with appropriate uncertainty' },
    { slug: 'wellness-experiment', title: 'Wellness Experiment', prereqSlugs: ['science-and-evidence', 'wellness-as-a-system'], summary: 'Run a low-risk personal observation with one change, one measure, and clear limits.', lesson: 'A wellness experiment is a structured self-observation. It can teach fit and feasibility when the change is small, the measure is clear, and the conclusion stays close to the data.', practice: 'Choose one routine change for seven days, define one measure, record context, and write what the result can and cannot tell you.', outcome: 'design a low-risk wellness observation with a measure and limit' },
  ]),
  lane('research', ['research-statistics', 'foundations'], [
    { slug: 'variables-and-measures', title: 'Variables and Measures', prereqSlugs: ['science-and-evidence'], summary: 'Translate broad ideas into variables that a study can observe and record.', lesson: 'A variable can change across people, times, or conditions. A measure gives the variable an observable form, such as a count, rating, duration, or response.', practice: 'Choose one broad idea and list three possible measures. Compare what each measure captures and leaves out.', outcome: 'distinguish a broad construct from an observable measure' },
    { slug: 'operational-definitions', title: 'Operational Definitions', prereqSlugs: ['variables-and-measures'], summary: 'Define a research idea in terms another person could measure consistently.', lesson: 'An operational definition describes the procedure used to observe a construct. Clear definitions support replication, comparison, and honest discussion of measurement limits.', practice: 'Define "focus during homework" in two measurable ways and explain the tradeoff between them.', outcome: 'write an operational definition for a simple research construct' },
    { slug: 'sampling-and-generalization', title: 'Sampling and Generalization', prereqSlugs: ['variables-and-measures', 'study-design-basics'], summary: 'Study how a sample supports or limits claims about a wider population.', lesson: 'A sample is the observed group, while a population is the group a claim hopes to describe. Selection, size, participation, and setting all affect generalization.', practice: 'Compare two ways to recruit students for a survey and predict how each could shape the result.', outcome: 'explain how sampling affects the reach of a research claim' },
    { slug: 'survey-question-design', title: 'Survey Question Design', prereqSlugs: ['variables-and-measures', 'study-design-basics'], summary: 'Write survey questions that are clear, bounded, and matched to the intended measure.', lesson: 'Good survey questions use familiar language, one idea at a time, clear time frames, and response options that fit the experience. Wording can shape the data.', practice: 'Rewrite three vague survey questions with a time frame, one construct, and balanced response options.', outcome: 'improve a survey question by aligning wording and measurement' },
    { slug: 'reliability-and-validity', title: 'Reliability and Validity', prereqSlugs: ['operational-definitions', 'study-design-basics'], summary: 'Compare consistency of measurement with how well a measure represents the intended idea.', lesson: 'Reliability asks whether a measure is consistent. Validity asks whether the measure supports the interpretation being made. A measure can be consistent and still capture the wrong thing.', practice: 'Evaluate a simple mood rating for consistency, meaning, and missing context across three uses.', outcome: 'distinguish reliability from validity in a measurement example' },
    { slug: 'effect-sizes-and-uncertainty', title: 'Effect Sizes and Uncertainty', prereqSlugs: ['descriptive-statistics', 'correlation-and-causation'], summary: 'Describe how large a difference or relationship appears and how much confidence the estimate deserves.', lesson: 'An effect size gives scale to a result. Uncertainty reflects variation, sample information, and measurement limits. A statistically impressive result can still have a small practical effect.', practice: 'Compare two hypothetical study results with the same direction and different sizes. Write what each could mean in daily life.', outcome: 'describe why magnitude and uncertainty belong beside a statistical result' },
    { slug: 'probability-and-risk', title: 'Probability and Risk', prereqSlugs: ['descriptive-statistics', 'correlation-and-causation'], summary: 'Use chance, base rates, and denominators to describe risk more clearly.', lesson: 'Probability describes how often an outcome may occur across a defined set of possibilities. Risk communication improves when it gives the reference group, time frame, and denominator.', practice: 'Rewrite one percentage claim with its denominator and time frame. Compare the same risk as a proportion and a frequency.', outcome: 'communicate a risk with a denominator, time frame, and reference group' },
    { slug: 'statistical-significance', title: 'Statistical Significance', prereqSlugs: ['effect-sizes-and-uncertainty', 'study-design-basics'], summary: 'Learn what a significance test can suggest and why it cannot replace effect size or judgment.', lesson: 'A significance test asks how surprising data would be under a specified model. The result depends on assumptions, sample size, and analysis choices, so interpretation also needs magnitude and context.', practice: 'Read a fictional result and write three separate notes: statistical evidence, practical size, and remaining uncertainty.', outcome: 'separate statistical significance from practical importance' },
    { slug: 'replication-and-open-science', title: 'Replication and Open Science', prereqSlugs: ['reading-a-research-claim', 'study-design-basics'], summary: 'Study how repeated tests, transparent methods, and shared materials strengthen research.', lesson: 'Replication asks whether a finding appears again under a similar or extended design. Open materials, clear analysis plans, and accessible data make inspection and learning easier.', practice: 'Create a replication checklist with the question, sample, measures, procedure, analysis, and limits.', outcome: 'explain how replication and transparency improve confidence in a finding' },
    { slug: 'research-poster', title: 'Research Poster', prereqSlugs: ['reading-a-research-claim', 'media-literacy-and-evidence'], summary: 'Turn a small research project into a clear visual story with question, method, result, and limit.', lesson: 'A research poster guides a reader through a bounded claim. Strong structure keeps the question, method, data display, interpretation, and limitation easy to find.', practice: 'Sketch a one-page poster for a low-risk observation project and label each section before adding design details.', outcome: 'organize a research project into a concise and evidence-matched presentation' },
  ]),
  lane('communication', ['communication', 'social-psychology'], [
    { slug: 'communication-basics', title: 'Communication Basics', prereqSlugs: ['social-influence-and-groups', 'emotional-vocabulary'], summary: 'Study how messages, context, feedback, and interpretation shape shared understanding.', lesson: 'Communication includes a sender, message, medium, receiver, context, and feedback. Meaning depends on words, timing, relationship, expectations, and the information each person brings.', practice: 'Describe one confusing exchange and separate the message, context, interpretation, and missing feedback.', outcome: 'identify the main parts of a communication exchange' },
    { slug: 'listening-and-feedback', title: 'Listening and Feedback', prereqSlugs: ['communication-basics'], summary: 'Use attention, reflection, questions, and specific observations to improve conversations.', lesson: 'Listening includes receiving words, checking meaning, and making room for the other person’s perspective. Feedback is clearest when it names an observable action and its effect.', practice: 'In one conversation, reflect the message before responding and offer one specific observation with a constructive next step.', outcome: 'use reflection and specific feedback in a conversation' },
    { slug: 'conflict-and-repair', title: 'Conflict and Repair', prereqSlugs: ['communication-basics', 'emotional-boundaries'], summary: 'Understand conflict as a process and practice repair through facts, impact, responsibility, and requests.', lesson: 'Conflict can involve different needs, interpretations, resources, or values. Repair begins with accurate description, listening, accountability, and an agreement about what happens next.', practice: 'Write a repair message with four parts: what happened, impact, responsibility, and a specific request.', outcome: 'create a repair message that includes impact and a next request' },
    { slug: 'assertive-communication', title: 'Assertive Communication', prereqSlugs: ['communication-basics', 'values-and-emotion'], summary: 'Express needs and limits with direct language, respect, and room for another person’s agency.', lesson: 'Assertive communication states facts, feelings, needs, limits, and requests clearly. It avoids guessing another person’s motives and leaves space for a response.', practice: 'Turn one indirect request into a sentence with a situation, need, boundary, and request.', outcome: 'state a need or limit using clear and respectful language' },
    { slug: 'group-norms', title: 'Group Norms', prereqSlugs: ['social-influence-and-groups'], summary: 'Make the expectations that guide a group visible, discussable, and revisable.', lesson: 'Norms are shared expectations about behavior. Explicit norms can protect participation, evidence, safety, and belonging when a group reviews them together.', practice: 'Draft five norms for a study group and add one process for revising them after a month.', outcome: 'write group norms that support participation and revision' },
    { slug: 'conformity-and-independence', title: 'Conformity and Independence', prereqSlugs: ['group-norms', 'cognitive-biases-and-decisions'], summary: 'Study how belonging, uncertainty, and evidence influence agreement with a group.', lesson: 'People may align with a group to gain information, approval, or coordination. Independent judgment becomes easier when a group invites private thinking and dissenting evidence.', practice: 'Before a group decision, write your own answer and one fact that could change it. Compare the process afterward.', outcome: 'identify a group pressure and design a step that protects independent judgment' },
    { slug: 'leadership-and-facilitation', title: 'Leadership and Facilitation', prereqSlugs: ['group-norms', 'listening-and-feedback'], summary: 'Guide a group through goals, participation, evidence, decisions, and review.', lesson: 'Facilitation shapes process rather than owning every answer. A facilitator clarifies the goal, distributes airtime, tracks decisions, and invites a review of what the group learned.', practice: 'Facilitate a ten-minute discussion with an agenda, one inclusion move, one evidence question, and a closing summary.', outcome: 'use a basic facilitation sequence for a small group' },
    { slug: 'friendship-and-support', title: 'Friendship and Support', prereqSlugs: ['social-connectedness', 'communication-basics'], summary: 'Explore reciprocity, trust, boundaries, and practical support in friendships.', lesson: 'Supportive relationships include attention, reliability, honesty, shared activity, and respect for limits. Different friendships can offer different forms of connection.', practice: 'Map one relationship’s strengths, needs, and boundaries. Choose one small action that supports reciprocity.', outcome: 'describe how trust, reciprocity, and boundaries shape support' },
    { slug: 'online-identity-and-audiences', title: 'Online Identity and Audiences', prereqSlugs: ['communication-basics', 'media-literacy-and-evidence'], summary: 'Study how platforms, audiences, permanence, and context shape online self-presentation.', lesson: 'Online identity is built through messages, images, interactions, platform design, and imagined audiences. A post can travel across contexts, so intentional sharing includes privacy and future effects.', practice: 'Choose one post format and list its intended audience, possible audiences, private details, and future interpretation.', outcome: 'identify audience and context factors in an online communication choice' },
    { slug: 'community-research', title: 'Community Research', prereqSlugs: ['friendship-and-support', 'study-design-basics'], summary: 'Ask community questions with listening, consent, shared ownership, and useful feedback.', lesson: 'Community research begins with relationships and a question that matters to participants. Good projects share decisions, protect privacy, return findings, and make room for local knowledge.', practice: 'Draft a low-risk community question, a consent statement, three listening prompts, and a plan to share results.', outcome: 'outline a respectful community research process' },
  ]),
  lane('decision', ['decision-making', 'media-literacy'], [
    { slug: 'heuristics-and-shortcuts', title: 'Heuristics and Shortcuts', prereqSlugs: ['cognitive-biases-and-decisions'], summary: 'Study mental shortcuts that make decisions faster and create predictable blind spots.', lesson: 'Heuristics use limited information to reach a workable judgment. They can save time, especially in familiar settings, while their limits become important when stakes, novelty, or uncertainty rise.', practice: 'Describe one quick judgment, the cue it used, the information it skipped, and a check that would improve it.', outcome: 'identify a heuristic and one condition where a second check helps' },
    { slug: 'probability-intuition', title: 'Probability Intuition', prereqSlugs: ['heuristics-and-shortcuts', 'probability-and-risk'], summary: 'Compare intuitive chance judgments with base rates, sample size, and explicit calculation.', lesson: 'Intuition often reacts to vividness and recent experience. Base rates, denominators, and repeated observations give a decision a wider reference frame.', practice: 'Estimate the chance of three simple events before calculating or looking up the base rate. Compare the estimates and write why they differed.', outcome: 'compare an intuitive probability judgment with a base-rate check' },
    { slug: 'sunk-cost-and-escalation', title: 'Sunk Costs and Escalation', prereqSlugs: ['heuristics-and-shortcuts', 'operant-conditioning-and-habits'], summary: 'Recognize when past investment pulls attention away from future value and current choices.', lesson: 'A sunk cost is a past investment that cannot be recovered. Good decisions focus on future benefits, costs, values, and alternatives while still learning from what happened.', practice: 'Write a decision in two columns: past investment and future choice. Decide what evidence belongs in each column.', outcome: 'separate past investment from the future value of a choice' },
    { slug: 'defaults-and-choice-architecture', title: 'Defaults and Choice Architecture', prereqSlugs: ['heuristics-and-shortcuts', 'health-behavior-basics'], summary: 'Study how the arrangement of options, defaults, friction, and reminders shapes behavior.', lesson: 'Choice architecture changes what is easy, visible, immediate, or automatic. Ethical design preserves meaningful choice and makes important consequences understandable.', practice: 'Redesign one study or wellness setting with a helpful default, lower friction, and a visible opt-out.', outcome: 'identify how a default or friction changes a choice environment' },
    { slug: 'misinformation-and-belief', title: 'Misinformation and Belief', prereqSlugs: ['media-literacy-and-evidence', 'cognitive-biases-and-decisions'], summary: 'Trace how repetition, emotion, identity, and weak source checks can shape belief.', lesson: 'Misinformation can spread through inaccurate content, missing context, or misleading framing. People process claims through attention, memory, trust, and group belonging.', practice: 'Choose one surprising claim and record the source, evidence, emotional cue, audience, and one unanswered question.', outcome: 'analyze several forces that can shape belief in a claim' },
    { slug: 'source-checking-workflow', title: 'Source-Checking Workflow', prereqSlugs: ['media-literacy-and-evidence'], summary: 'Use a repeatable sequence for checking an author, source, date, evidence, and context.', lesson: 'A source check moves from claim to origin, method, date, comparison, and limits. The workflow protects time by stopping when the evidence cannot answer the question.', practice: 'Run one article through the workflow and write a two-sentence conclusion with one supported claim and one open question.', outcome: 'apply a source-checking sequence to a public claim' },
    { slug: 'visualizing-data', title: 'Visualizing Data', prereqSlugs: ['descriptive-statistics', 'media-literacy-and-evidence'], summary: 'Choose charts, labels, scales, and comparisons that help readers see the data accurately.', lesson: 'A chart is an argument about what deserves attention. Titles, axes, units, colors, missing values, and comparison groups can clarify or distort interpretation.', practice: 'Make two charts from the same small data set, then write how the design changes what a reader notices.', outcome: 'identify how chart design affects interpretation of a data set' },
    { slug: 'risk-communication', title: 'Risk Communication', prereqSlugs: ['source-checking-workflow', 'probability-and-risk'], summary: 'Explain uncertain outcomes with numbers, context, action options, and respectful language.', lesson: 'Risk communication works when people can see the event, time frame, comparison, uncertainty, and available action. Tone and trust affect whether information can be used.', practice: 'Rewrite one risk statement for a middle-school reader using a frequency, a time frame, and one practical next step.', outcome: 'communicate an uncertain risk with context and an action option' },
    { slug: 'prediction-and-calibration', title: 'Prediction and Calibration', prereqSlugs: ['probability-and-risk', 'reading-a-research-claim'], summary: 'Make forecasts, record confidence, and compare predictions with outcomes over time.', lesson: 'Calibration improves when confidence matches accuracy across many forecasts. A prediction log makes memory less selective and turns mistakes into data for better judgment.', practice: 'Make five low-stakes predictions with probabilities and dates. Review the outcomes and compare confidence with accuracy.', outcome: 'use a prediction log to compare confidence and outcomes' },
    { slug: 'decision-journal', title: 'Decision Journal', prereqSlugs: ['cognitive-biases-and-decisions', 'values-clarification'], summary: 'Record goals, options, evidence, uncertainty, and review dates before important choices.', lesson: 'A decision journal captures reasoning before the outcome is known. Reviewing it later separates decision quality from luck and reveals patterns in assumptions.', practice: 'Use a one-page journal for one meaningful choice and schedule a future review date.', outcome: 'record a decision process with evidence, uncertainty, and a review plan' },
  ]),
  lane('public-health', ['public-health', 'wellness-science'], [
    { slug: 'public-health-basics', title: 'Public Health Basics', prereqSlugs: ['wellness-as-a-system', 'social-connectedness'], summary: 'Study how health patterns and protective conditions affect groups of people.', lesson: 'Public health looks at prevention, environments, systems, and population patterns alongside individual care. It asks what conditions make healthy choices more possible for more people.', practice: 'Choose a common health concern and list an individual action, a school or workplace action, and a community action.', outcome: 'distinguish individual and population approaches to health' },
    { slug: 'social-determinants-of-health', title: 'Social Determinants of Health', prereqSlugs: ['public-health-basics'], summary: 'Explore how housing, education, income, safety, transportation, and connection shape health opportunities.', lesson: 'Health is influenced by conditions where people live, learn, work, and gather. Naming these conditions helps a project address access and context alongside personal behavior.', practice: 'Map one health opportunity across five settings and identify one barrier and one protective condition in each.', outcome: 'name several social and environmental conditions that shape health opportunities' },
    { slug: 'health-inequities', title: 'Health Inequities', prereqSlugs: ['social-determinants-of-health'], summary: 'Study patterned differences in health opportunity and the systems that produce them.', lesson: 'Health inequities are shaped by policy, resources, exposure, discrimination, and access. A careful analysis describes patterns and mechanisms while centering affected communities.', practice: 'Read a public data table and list the group comparison, possible context, missing data, and question for community input.', outcome: 'interpret a health difference with context and a systems lens' },
    { slug: 'prevention-and-protection', title: 'Prevention and Protection', prereqSlugs: ['public-health-basics'], summary: 'Compare prevention levels and protective actions across individual, group, and community settings.', lesson: 'Prevention can reduce exposure, identify a concern early, or limit impact after it appears. Protection can include information, design, access, policy, and supportive relationships.', practice: 'Choose one issue and create a prevention ladder with an upstream condition, an early action, and a support after impact.', outcome: 'compare several prevention and protection approaches' },
    { slug: 'risk-and-protective-factors', title: 'Risk and Protective Factors', prereqSlugs: ['public-health-basics', 'stress-basics'], summary: 'Map conditions that can raise challenge exposure or strengthen support and adaptation.', lesson: 'Risk and protective factors are context-dependent. A factor can change across settings, and protective systems work best when people can actually access them.', practice: 'Build a two-column map for a student challenge and add one protective factor at home, school, and community level.', outcome: 'map risk and protective factors across multiple settings' },
    { slug: 'health-messages-and-trust', title: 'Health Messages and Trust', prereqSlugs: ['public-health-basics', 'media-literacy-and-evidence'], summary: 'Design health information that respects evidence, audience, culture, uncertainty, and trust.', lesson: 'People use health messages through existing relationships and experiences. Clear sources, practical actions, transparent uncertainty, and community partnership can strengthen understanding.', practice: 'Rewrite one health message for two audiences and explain the evidence, action, uncertainty, and trust cue in each version.', outcome: 'adapt a health message while preserving evidence and context' },
    { slug: 'community-health-data', title: 'Community Health Data', prereqSlugs: ['public-health-basics', 'descriptive-statistics'], summary: 'Read population data with attention to denominators, time, geography, missingness, and lived experience.', lesson: 'Community data can reveal patterns while hiding variation within groups. Good interpretation pairs numbers with definitions, context, and questions from people represented by the data.', practice: 'Choose one public chart and annotate its population, time frame, measure, comparison, missing information, and possible action.', outcome: 'interpret community health data with clear definitions and limits' },
    { slug: 'health-program-evaluation', title: 'Health Program Evaluation', prereqSlugs: ['community-health-data', 'study-design-basics'], summary: 'Ask whether a program reached its audience, delivered its activities, and showed the intended pattern.', lesson: 'Evaluation connects program goals with process measures, reach, outcomes, comparison, and feedback. A useful result can guide improvement even when it cannot prove every cause.', practice: 'Create an evaluation table with one goal, one reach measure, one process measure, one outcome, and one feedback question.', outcome: 'outline a simple evaluation plan for a community program' },
    { slug: 'public-health-ethics', title: 'Public Health Ethics', prereqSlugs: ['public-health-basics', 'consent-and-autonomy'], summary: 'Balance benefit, harm, fairness, freedom, privacy, and community voice in health decisions.', lesson: 'Public health choices can affect many people at once. Ethical reasoning makes the values, evidence, burdens, benefits, and least-restrictive options visible.', practice: 'Use an ethics grid to compare a proposed policy’s benefits, burdens, affected groups, evidence, and revision plan.', outcome: 'identify competing ethical values in a population-level health decision' },
    { slug: 'community-wellness-project', title: 'Community Wellness Project', prereqSlugs: ['health-program-evaluation', 'public-health-ethics'], summary: 'Design a small, consent-aware project that responds to a community-defined wellness question.', lesson: 'A community wellness project combines listening, evidence, design, evaluation, and shared ownership. The project should fit the setting and return useful information to participants.', practice: 'Draft a project brief with a community question, partners, low-risk activity, measure, consent plan, and return-of-results plan.', outcome: 'design a small community wellness project with evaluation and ethics built in' },
  ]),
  lane('creativity', ['creativity', 'focus'], [
    { slug: 'creativity-and-cognition', title: 'Creativity and Cognition', prereqSlugs: ['thinking-and-cognition'], summary: 'Study how attention, memory, knowledge, curiosity, and constraints participate in creative work.', lesson: 'Creative thinking combines existing material in useful or surprising ways. Knowledge supplies ingredients, attention selects details, and constraints can focus exploration.', practice: 'Choose an ordinary object and list ten new uses in five minutes. Circle the ideas that solve a real problem.', outcome: 'name several cognitive processes that support creative work' },
    { slug: 'divergent-thinking', title: 'Divergent Thinking', prereqSlugs: ['creativity-and-cognition'], summary: 'Generate multiple possibilities before selecting a direction.', lesson: 'Divergent thinking expands options through fluency, flexibility, originality, and elaboration. Evaluation belongs after idea generation so early judgment stays open during the search.', practice: 'Generate twenty ideas for improving a shared space, then group them by approach and choose three to develop.', outcome: 'use a divergent process to create and organize multiple ideas' },
    { slug: 'convergent-thinking', title: 'Convergent Thinking', prereqSlugs: ['divergent-thinking'], summary: 'Select and refine ideas using goals, constraints, evidence, and audience needs.', lesson: 'Convergent thinking narrows a field of options. Clear criteria make selection easier to explain and help a creator revise the chosen idea.', practice: 'Choose three criteria for a project, score five ideas, and write why the strongest option fits the context.', outcome: 'select a creative idea using explicit criteria' },
    { slug: 'creative-routines', title: 'Creative Routines', prereqSlugs: ['creativity-and-cognition', 'habit-cues-and-context'], summary: 'Build repeatable conditions that make creative practice easier to start.', lesson: 'Creative routines use cues, time blocks, materials, and a small opening action. The routine protects practice from waiting for a perfect mood.', practice: 'Design a ten-minute creative routine with a cue, workspace, first action, and stopping point.', outcome: 'design a repeatable routine for creative practice' },
    { slug: 'feedback-and-creative-work', title: 'Feedback and Creative Work', prereqSlugs: ['creative-routines', 'feedback-and-learning'], summary: 'Use feedback to strengthen a creative work while preserving the creator’s purpose.', lesson: 'Useful creative feedback names the intended effect, the observed effect, a specific moment, and a possible revision. The creator decides which feedback fits the purpose.', practice: 'Give feedback on a small work using one strength, one observed effect, one question, and one revision option.', outcome: 'give specific and purpose-aware feedback on creative work' },
    { slug: 'identity-and-context', title: 'Identity and Context', prereqSlugs: ['personality-basics', 'social-influence-and-groups'], summary: 'Explore how identity is shaped through personal history, relationships, roles, and social context.', lesson: 'Identity includes self-understanding and the roles people move through. Context can make different parts of identity more visible, valued, challenged, or supported.', practice: 'Draw an identity map with roles, communities, values, and contexts. Mark where support or tension appears.', outcome: 'describe how identity and context influence one another' },
    { slug: 'lifespan-and-learning', title: 'Lifespan and Learning', prereqSlugs: ['identity-and-context', 'memory-and-recall'], summary: 'Study learning, relationships, and change across different life stages.', lesson: 'Development unfolds through biology, learning, relationships, culture, and historical context. People can keep learning while needs, responsibilities, and opportunities change.', practice: 'Compare how one skill might be learned by a child, teenager, adult, and older adult in different settings.', outcome: 'describe development as change shaped by people and context across time' },
    { slug: 'adolescence-and-brain', title: 'Adolescence and the Brain', prereqSlugs: ['lifespan-and-learning', 'brain-and-behavior'], summary: 'Explore adolescence through brain development, social context, learning, and growing autonomy.', lesson: 'Adolescence includes changing cognitive capacities, relationships, identity, sleep, and social roles. A balanced account includes both support needs and growing agency.', practice: 'Design a school routine that supports sleep, autonomy, connection, and learning for adolescent students.', outcome: 'connect adolescent development with context, support, and agency' },
    { slug: 'college-transition-and-wellness', title: 'College Transition and Wellness', prereqSlugs: ['lifespan-and-learning', 'wellness-as-a-system'], summary: 'Plan for changing routines, belonging, workload, resources, and support during a college transition.', lesson: 'Transitions change time, place, relationships, identity, and available services. A wellness plan names routines to protect, people to contact, and systems to learn.', practice: 'Create a transition map with one academic support, one social support, one recovery routine, and one financial or logistical question.', outcome: 'build a practical wellness map for a major transition' },
    { slug: 'purpose-and-contribution', title: 'Purpose and Contribution', prereqSlugs: ['values-clarification', 'creativity-and-cognition'], summary: 'Connect values, strengths, relationships, and useful action to a sense of contribution.', lesson: 'Purpose becomes clearer through repeated choices and contribution. It can grow from care for people, questions, craft, justice, learning, or place.', practice: 'List three values, three strengths, and three community needs. Draft one small contribution that overlaps them.', outcome: 'connect values and strengths with one concrete contribution' },
  ]),
  lane('lifespan', ['lifespan-development', 'foundations'], [
    { slug: 'developmental-perspectives', title: 'Developmental Perspectives', prereqSlugs: ['lifespan-and-learning'], summary: 'Compare biological, cognitive, social, cultural, and ecological views of development.', lesson: 'Developmental perspectives ask how people change and what shapes those changes. Each perspective highlights some mechanisms and leaves questions for the others.', practice: 'Explain one life-stage change using three perspectives and identify where their explanations overlap.', outcome: 'compare several perspectives on development' },
    { slug: 'attachment-and-connection', title: 'Attachment and Connection', prereqSlugs: ['developmental-perspectives', 'social-connectedness'], summary: 'Study how dependable relationships support exploration, comfort, and social learning.', lesson: 'Early and ongoing relationships can shape expectations about safety, support, and connection. Relationships remain changeable through new experiences, repair, and context.', practice: 'Map the support signals that help someone feel safe enough to learn or explore in a new setting.', outcome: 'describe how connection can support exploration and learning' },
    { slug: 'language-and-development', title: 'Language and Development', prereqSlugs: ['developmental-perspectives', 'communication-basics'], summary: 'Explore how language, conversation, culture, and interaction support thinking and belonging.', lesson: 'Language carries concepts, relationships, memories, and cultural knowledge. Development grows through interaction with people and environments that offer meaningful communication.', practice: 'Observe a conversation or story and identify one way language carries information, emotion, and social connection.', outcome: 'identify cognitive and social roles of language across development' },
    { slug: 'play-and-learning', title: 'Play and Learning', prereqSlugs: ['developmental-perspectives', 'creativity-and-cognition'], summary: 'Study how play supports exploration, practice, imagination, rules, and social learning.', lesson: 'Play creates a low-stakes space for trying possibilities, negotiating rules, and practicing skills. Different materials and cultures create different play opportunities.', practice: 'Design a ten-minute activity that lets learners choose, test, revise, and explain a strategy.', outcome: 'connect play with exploration, practice, and social learning' },
    { slug: 'identity-development', title: 'Identity Development', prereqSlugs: ['identity-and-context', 'developmental-perspectives'], summary: 'Explore how identity stories change through reflection, relationships, roles, and future possibilities.', lesson: 'Identity develops through continuity and revision. People interpret their history, test roles, receive feedback, and choose commitments within social and cultural contexts.', practice: 'Write a past, present, and future version of one identity story, then identify the values that connect them.', outcome: 'describe identity as an evolving story shaped by context and choice' },
    { slug: 'moral-development', title: 'Moral Development', prereqSlugs: ['developmental-perspectives', 'ethics-and-everyday-decisions'], summary: 'Study how people reason about care, fairness, rules, consequences, and responsibility.', lesson: 'Moral reasoning can draw on relationships, social rules, rights, outcomes, and principles. Development includes expanding the ability to consider perspectives and consequences.', practice: 'Compare two solutions to a low-stakes dilemma using care, fairness, rule, and outcome lenses.', outcome: 'compare several lenses for moral reasoning' },
    { slug: 'aging-and-learning', title: 'Aging and Learning', prereqSlugs: ['lifespan-and-learning', 'brain-plasticity'], summary: 'Explore learning, memory, roles, and connection across later life.', lesson: 'Aging includes variation in health, experience, environment, relationships, and opportunity. Learning continues through practice, meaning, adaptation, and access to supportive settings.', practice: 'Design an intergenerational learning activity that values experience and offers multiple ways to participate.', outcome: 'describe how later-life learning depends on variation and access' },
    { slug: 'developmental-contexts', title: 'Developmental Contexts', prereqSlugs: ['developmental-perspectives', 'social-determinants-of-health'], summary: 'Connect life-stage change with family, school, neighborhood, culture, policy, and historical conditions.', lesson: 'Development occurs inside nested contexts. A person’s opportunities can change when institutions, resources, relationships, or social expectations change.', practice: 'Draw a context map for one learner with home, school, community, technology, and policy influences.', outcome: 'map several contexts that shape development and opportunity' },
    { slug: 'intergenerational-learning', title: 'Intergenerational Learning', prereqSlugs: ['aging-and-learning', 'communication-basics'], summary: 'Design learning exchanges that value knowledge across age groups.', lesson: 'Different generations hold different experiences, skills, histories, and questions. Mutual teaching can build connection when the exchange respects agency and avoids stereotypes.', practice: 'Plan a paired activity where each participant teaches one skill and asks one genuine question.', outcome: 'design an intergenerational learning exchange with mutual roles' },
    { slug: 'life-stage-transition-plan', title: 'Life-Stage Transition Plan', prereqSlugs: ['developmental-contexts', 'college-transition-and-wellness'], summary: 'Use values, support, routines, and information to navigate a changing life stage.', lesson: 'A transition plan makes change concrete. It names what is ending, what is beginning, what support exists, and what experiment can make the next step clearer.', practice: 'Create a transition page with three changes, three supports, two questions, and one small action this week.', outcome: 'create a support-aware plan for a life-stage transition' },
  ]),
  lane('ethics', ['ethics-society', 'decision-making'], [
    { slug: 'ethics-and-everyday-decisions', title: 'Ethics and Everyday Decisions', prereqSlugs: ['decision-journal'], summary: 'Use values, duties, consequences, care, and fairness to reason through ordinary choices.', lesson: 'Ethics asks what people ought to do and why. Multiple frameworks can reveal different parts of a choice, especially when values conflict.', practice: 'Use four lenses on one everyday dilemma and write which value each lens makes visible.', outcome: 'compare several ethical lenses in an everyday decision' },
    { slug: 'values-and-tradeoffs', title: 'Values and Tradeoffs', prereqSlugs: ['ethics-and-everyday-decisions', 'values-clarification'], summary: 'Make competing values visible when every available option has a cost.', lesson: 'A tradeoff occurs when advancing one value affects another. Naming the conflict and the affected people creates room for transparent priorities and revision.', practice: 'Draw a tradeoff map with two values, three options, affected people, and one fair process for choosing.', outcome: 'explain a value conflict and the tradeoff inside a choice' },
    { slug: 'fairness-and-equity', title: 'Fairness and Equity', prereqSlugs: ['values-and-tradeoffs', 'health-inequities'], summary: 'Compare equal treatment, equitable support, procedural fairness, and outcomes.', lesson: 'Fairness can concern rules, opportunity, treatment, voice, and results. Equity asks what different people need to participate meaningfully under different conditions.', practice: 'Review a shared-resource scenario and propose an equal option, an equity option, and a process for feedback.', outcome: 'distinguish equal treatment from equity and procedural fairness' },
    { slug: 'consent-and-autonomy', title: 'Consent and Autonomy', prereqSlugs: ['ethics-and-everyday-decisions', 'study-design-basics'], summary: 'Study informed choice, capacity, voluntariness, and the right to change one’s mind.', lesson: 'Consent requires understandable information, a real choice, and respect for a person’s decision. Autonomy grows when people can ask questions, pause, and withdraw.', practice: 'Write a plain-language consent explanation for a low-risk school project, including purpose, activity, privacy, and withdrawal.', outcome: 'identify the parts of informed and voluntary consent' },
    { slug: 'privacy-and-research', title: 'Privacy and Research', prereqSlugs: ['consent-and-autonomy', 'reading-a-research-claim'], summary: 'Balance useful data with privacy, confidentiality, minimization, and participant control.', lesson: 'Privacy protects people from unwanted exposure and misuse of information. Ethical research collects what it needs, explains access, limits identifiers, and plans deletion or retention.', practice: 'Create a privacy table for a small survey with data collected, reason, access, risk, and deletion plan.', outcome: 'design a basic privacy plan for a low-risk research project' },
    { slug: 'privacy-and-data', title: 'Privacy and Data', prereqSlugs: ['privacy-and-research', 'source-checking-workflow'], summary: 'Understand how data traces, metadata, defaults, and sharing choices shape privacy.', lesson: 'Data can reveal patterns through direct details and combinations of small details. Privacy choices involve collection, storage, access, inference, and future use.', practice: 'Audit one app or school tool for collected data, permissions, audience, retention, and one safer setting.', outcome: 'identify several stages where personal data can gain exposure' },
    { slug: 'algorithmic-recommendations', title: 'Algorithmic Recommendations', prereqSlugs: ['privacy-and-data', 'source-checking-workflow'], summary: 'Study how recommendation systems use signals, objectives, feedback, and user data.', lesson: 'A recommendation system ranks possible content using a model and an objective. Feedback loops can narrow exposure, reward attention, or amplify patterns already present in the data.', practice: 'Draw a recommendation loop with user signal, ranking objective, result, feedback, and one possible bias.', outcome: 'describe the parts and risks of a recommendation loop' },
    { slug: 'ai-and-human-judgment', title: 'Ai and Human Judgment', prereqSlugs: ['algorithmic-recommendations', 'brain-science-claims'], summary: 'Compare automated outputs with human judgment, evidence, accountability, and context.', lesson: 'An AI output is a produced result shaped by data, objective, model, prompt, and evaluation. Human judgment remains responsible for context, values, privacy, and consequences.', practice: 'Evaluate a fictional automated suggestion with five questions: goal, evidence, uncertainty, affected people, and human review.', outcome: 'identify where human judgment and accountability belong around an AI output' },
    { slug: 'technology-and-attention', title: 'Technology and Attention', prereqSlugs: ['ai-and-human-judgment', 'digital-mindfulness'], summary: 'Analyze how digital tools shape attention, choice, social connection, and recovery.', lesson: 'Technology changes the cues and rewards around attention. Good design makes goals visible, supports control, and gives people meaningful choices about interruptions and data.', practice: 'Redesign one digital routine with an attention goal, notification rule, recovery break, and privacy check.', outcome: 'connect technology design with attention and personal agency' },
    { slug: 'civic-dialogue', title: 'Civic Dialogue', prereqSlugs: ['conflict-and-repair', 'ethics-and-everyday-decisions'], summary: 'Practice evidence-aware conversation across disagreement, identity, values, and public decisions.', lesson: 'Civic dialogue combines listening, evidence, shared rules, uncertainty, and a search for workable action. Agreement is one possible outcome; understanding and a fair process are also outcomes.', practice: 'Prepare a dialogue with a shared question, two evidence sources, one curiosity question, and a process for handling conflict.', outcome: 'plan a respectful dialogue that includes evidence and a fair process' },
  ]),
];

export const EXPANSION_150_GUIDES = EXPANSION_LANES.flatMap((entry) =>
  entry.rows.map((row) => ({ ...row, sourceKey: entry.sourceKey, subjectIds: entry.subjectIds })),
);
